repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: mixed-line-ending
    - id: check-merge-conflict
    - id: check-yaml
      exclude: ^conf/lr_scheduler/plateau.yaml$

    # Block large files (optional, if you still want size checks for other types)
    - id: check-added-large-files
      args: ["--maxkb=2000"]
      exclude: '^Docs/.*\.(jpg|jpeg)$'

# - repo: https://github.com/psf/black
#   rev: 24.8.0
#   hooks:
#     - id: black
#       args: [--target-version=py38]

# - repo: https://github.com/astral-sh/ruff-pre-commit
#   rev: v0.6.9
#   hooks:
#     - id: ruff
#       args: [--fix]

exclude: '^(?:\.idea|data|results|temp|outputs|resources|__pycache__)/'
