defaults: # for loading the default.yaml config
  - task: panoptic

  - visualization: default
  - lr_scheduler: exponential
  - training: npm3d_benchmark/kpconv-panoptic #kpconv_panoptic
#
  - debugging: default
  - models: panoptic/kpconv
  - data: panoptic/npm3d-kpconv #panoptic/Italy-kpconv
  - sota # Contains current SOTA results on different datasets (extracted from papers !).
#  - hydra/job_logging: custom
#  - hydra/output: custom  # add the support for user-defined experiment folder (where to save the experiment files)

job_name: benchmark # prefix name for saving the experiment file.
model_name: KPConvPaperNPM3D # Name of the specific model to load
update_lr_scheduler_on: "on_epoch" # ["on_epoch", "on_num_batch", "on_num_sample"]
selection_stage: ""
pretty_print: False
eval_frequency: 1

tracker_options: # Extra options for the tracker
  full_res: False
  make_submission: False
  track_boxes: False
